### ISSUE TITLE
Question about the gel pad's setting

### ISSUE THREAD

**Issue by XiaodaoLin01** [Taccel-Simulator/Taccel#11]
Hello！I have some questions about the pad settings: if I load custom pads, do the physical parameters of those pads need to be set myself in the .json file, or are there already defaults in the code? Such as the following parameters: vbts_cfg.density, vbts_cfg. E, vbts_cfg.nu, vbts_cfg.mu.

**Comment by YuyangLee** [comment]
Hi, you can set the physical parameters when adding them to the `Model`. To do this, I recommend modifying the members in the `VBTSConfig` according to your own sensor in the current version.

The feature we're working on (mentioned in the last issue https://github.com/Taccel-Simulator/Taccel/issues/10) will make the parameter specification more centered and intuitive.

**Comment by g1n0st** [comment]
Hi @XiaodaoLin01,

Thanks again for your kind interest in our work! Regarding your note about “chaotic model loading” in the parallel environment — would you mind describing in more detail the specific behavior you're seeing on your machine, or sharing any error logs? That would help us better understand what's happening on your side.

Best,
Chang

**Comment by XiaodaoLin01** [comment]
Hello, it's a pleasure to hear from you.
RELEVANT PARAMETERS I RUN: PRISMATIC, num_envs=2.
When the code is run, the terminal displays: [WARNING] [Collision] Explode at frame 0.
But the code still works, just very slowly. () It can run 3 frames in about 10 hours. Looking at the exported .ply file, it was found that the model had irregular collisions. Sometimes the manipulator is large and small, sometimes the object collides with the hand, and sometimes the sensor of just one hand is very seriously deformed.
Also, during my debugging process, will
model.finalize() is adjusted to add_joint() to load the model correctly and allow action, but the object has no degrees of freedom.

Best,
lin

**Comment by g1n0st** [comment]
Hi @XiaodaoLin01, sorry for the late reply, I just got back to work. Thank you for narrowing down the potential issue. I’m currently trying to reproduce the script. Would you mind sharing some leap-sensor-related files to help me run it properly?

**Comment by g1n0st** [comment]
Hi @XiaodaoLin01, thanks for the quick reply! I’ve made some progress debugging the code and just want to double-check one thing—did you see any `[ERROR] Unexpected Recompilation` messages when running the code or you are using the code that is not the latest release?

**Comment by XiaodaoLin01** [comment]
I was so impressed! We'd be glad to hear from you.
Let me answer your questions one by one:
1. Display issues when running code.
When num_envs=2, the terminal will display: "RELEVANT PARAMETERS I RUN: PRISMATIC, num_envs=2.", but it will still continue to run, but it will be very slow, looking at the exported .ply file, it will be found that objects and hands in one environment will zoom in and out irregularly, and the hands and objects in the other environment will be normal in size, but the position is misaligned, and the tactile sensor is severely deformed, but there is a signal.
When num_envs=4, the terminal is normal and runs quickly, and the position of the model loads normally, but the gravitational and tactile signals are lost.
2. Regarding the error, I don't seem to notice that there is: "[ERROR] Unexpected Recompilation";
3. Regarding the version, I was one of the earliest followers and downloaded the documentation since 4.25. There was no update.

I hope my answers will help you.

Best,
Lin

**Comment by g1n0st** [comment]
Thank you for your quick reply! Based on your answers to points 2 and 3, I believe we’re encountering the same issue—some of the warp kernels used in the tac_man example was not compiled, so some code and behaviors were silently skipped.

In the latest release, this would trigger a [ERROR] Unexpected Recompilation message, but in the earlier version you’re using, this issue fails silently without any warning.

We’ll work to release a fix as soon as possible—hopefully later today. Really appreciate your patience!

Best,
Chang

**Comment by g1n0st** [comment]
Hi @XiaodaoLin01,

Thank you for your patience. We've just released a new version of Taccel (commit ed85528). Could you please update to the latest version and try again?

After the release, I spent some time reproducing your case using the script above and `leap.zip` (with `leap.urdf`) you provided. Unfortunately, I wasn’t able to reproduce the issues you mentioned in 1. Display issues (and the underlying simulation issues) when running code. In my tests—both with the new release and the earlier version you used—whether with 2 or 4 envs, the simulation seems to start in an abnormal state. Please see my attached screenshot.

I suspect this might be due to a misconfiguration on my side, so I’d appreciate it if you could test again on your setup. If the problem persists, feel free to ping me—I’ll continue looking into it.

Best,
Chang

<img width="637" alt="Image" src="https://github.com/user-attachments/assets/f5bfa301-8145-460e-ba90-4552c112082f" />

**Comment by XiaodaoLin01** [comment]
It was very touching to be able to hear back from you on Saturday.
We will try to update the latest version and get back to you with a message as soon as possible.

Best，
Lin

**Comment by XiaodaoLin01** [comment]
Hello. We have the latest version installed on our side and are able to run smoothly in a non-parallel environment - the same as the previous version.
Then, when switching to a parallel environment, it's still the same as in the case above:

- num_envs=2.", but it will continue to run, but it will be very slow, look at the exported .ply file, you will find that the objects and hands in one environment will be irregularly zoomed in and out, while the hands and objects in the other environment will be normal in size, but the position is misaligned, the tactile sensor is severely deformed, but there is a signal.

- When num_envs=4, the terminal is normal and fast, the model position loads normally, but the gravity and haptic signals are lost.

Also, it's worth noting that the frame 0 PLY file we exported in a non-parallel environment is the same as the image you uploaded, but the hand load is messed up (I switched to our Allegro as well). However, it does not affect the subsequent normal operation.
There is no “[ERROR] Unexpected Recompilation” in the whole process
So, I still think “add_world_prismatic_joint” function plays an effect on this?
Maybe you have other opinions? We look forward to hearing more with you.

Best，
Lin

**Comment by g1n0st** [comment]
Hi @XiaodaoLin01,

Thanks a lot for your quick test and detailed reply.

My main concern is that "the frame 0 PLY file we exported in a non-parallel environment is the same as the image you uploaded, but the hand load is messed up" — this suggests that the scene configuration itself might not be ideal.

When I tested your code, I tried removing the joint added by `add_world_prismatic_joint` and kept only the robot hand, but the exported scene still looked incorrect. So I may not think that function is the root cause here.

Some other cases (like [this one](https://github.com/Taccel-Simulator/Taccel/issues/9)) seem to load the robot hand correctly. Also, during testing, I encountered the message: `th_tip not connected via joints. Will add link to base frame.` — could you double-check whether the URDF you're using is correct?

If not, feel free to keep me posted!

Best,
Chang

**Comment by XiaodaoLin01** [comment]
Below is the code for a single environment, and you can see that it loads and outputs a tactile signal normally. So it can be stated that both the .urdf file and the location of the loaded object are reasonable. Hope to help you further troubleshoot the problem.

``` Python
import math
import os
import os.path as osp
import sys
from enum import Enum
import time

import cv2
import numpy as np
import open3d as o3d
import torch
import trimesh as tm
import warp as wp
from scipy.spatial.transform import Rotation as R
from tqdm.rich import tqdm_rich as tqdm

sys.path.append(".")

import argparse

from taccel.taccel import TaccelModel
from warp_ipc.body_handle import TetMeshBodyHandle
from warp_ipc.ipc_integrator import IPCIntegrator
from warp_ipc.joint_handle import WorldJointHandle, JointType
from warp_ipc.robots import Robot
from warp_ipc.utils import log

from taccel.utils.example_utils import init_robot_demo

def add_joint(
    model: TaccelModel,
    part_handle: TetMeshBodyHandle,
    joint: JointType,
    edge_verts=None,
) -> WorldJointHandle:
    match joint:
        case JointType.PRISMATIC:
            axis_z = 1.0
            axis_y, axis_x = 0.0, 0.0
            joint_axis = np.array([axis_x, axis_y, axis_z])
            joint_axis = joint_axis / np.linalg.norm(joint_axis)

            print(f"Creating prismatic joint towards {joint_axis}")
            joint_handle = model.add_world_prismatic_joint(part_handle, joint_axis)
            
        case JointType.HELICAL:
            print("Loaded nut and bolt to simulate a helical joint")
            model.enable_affine_kinematic_constraint(part_handle)
            joint_handle = None

        case _:
            raise NotImplementedError()

    return joint_handle

@torch.no_grad()
def run():
    wp.init()

    parser = argparse.ArgumentParser()
    parser.add_argument("--joint_type", default="prismatic", type=str)
    parser.add_argument("--seed", default=0, type=int)
    args = parser.parse_args()
    
    _, OUT_DIR = init_robot_demo(args, f"tac_man-{args.joint_type}-{args.seed}")

    model = TaccelModel(num_envs=1, viz_envs=[]) 
    joint_type = {
        "prismatic": JointType.PRISMATIC,
        "helical": JointType.HELICAL,
    }[args.joint_type] 
    # ============================== Setup Simulation Model ==============================
    model.gravity = wp.vec3d([0, 0, -9.8])
    model.dhat = 5e-4
   
    handle_extents = np.array([0.035, 0.075, 0.035]) * 2 
    obj_mesh = tm.primitives.Box(extents=handle_extents).to_mesh()
    obj_mesh.vertices = np.array(obj_mesh.vertices) + np.array([[-0.07, -0.08, 0.1]])
    kine_handle = model.add_affine_body(obj_mesh.vertices, obj_mesh.faces.astype(np.int32), 1e1, 1e9, 0.3)  

    floor_extents = np.array([0.2, 0.2, 0.002]) * 2 
    floor_mesh = tm.primitives.Box(extents=floor_extents).to_mesh() 
    floor_mesh.vertices = np.array(floor_mesh.vertices) + np.array([[-0.07, -0.08, 0.05]])
    floor_handle = model.add_affine_body(floor_mesh.vertices, floor_mesh.faces.astype(np.int32), 1e3, 1e9, 0.3)

    # =========== hand ===========
    urdf_path, _, tac_path = Robot.get_fabr_path("leap-sensor", 1e-07)
    # urdf_path, _, tac_path = Robot.get_fabr_path("tactile-allegro", 1e-07)
    model.add_robot(
        urdf_path,
        tac_fab_path=tac_path,
        env_id=0,
        start_coll_layer=2,
        coll_layers=[],
        disable_coll_layers=[1],
        use_collision_mesh = True,
    )
    joint_names = ["if_mcp", "if_rot", "if_pip", "if_dip",
                   "mf_mcp", "mf_rot", "mf_pip", "mf_dip",
                   "rf_mcp", "rf_rot", "rf_pip", "rf_dip",
                   "th_cmc", "th_axl", "th_mcp", "th_ipl"]
   
    initial_qpos = np.zeros(len(joint_names), dtype=np.float32)  
    
    initial_qpos = np.array([
        0, 0.3, 0.33, 0.05,
        0, 0.3, 0.33, 0.05,
        0, 0.3, 0.33, 0.05,
        0, -1.58, 0.2, -0.16
    ], dtype=np.float32)


    middle_qpos = np.array([
        0, 0.525, 0.58, 0.5,
        0, 0.525, 0.59, 0.5,
        0, 0.525, 0.59, 0.5,
        0, -1.62, 0.85, -0.79
    ], dtype=np.float32)

    model.add_vbts_to_sim(model.robots[0], coll_layers=1)
    model.init()   
   
    model.enable_affine_kinematic_constraint(floor_handle)
    model.set_affine_kinematic_target(
        floor_handle,
        np.eye(3),
        np.array([0, 0, 0])  
    )

    # model.enable_affine_kinematic_constraint(kine_handle)
    model.disable_affine_kinematic_constraint(kine_handle)
    model.set_affine_kinematic_target(
        kine_handle,
        np.eye(3),
        np.array([-0.07, -0.08, 0.1]) 
    )    
   
    joint_handle = add_joint(model, kine_handle, joint_type)

    hand_init_pos = np.array([0, 0.0, 0.2])
    hand_init_rot = R.from_euler("xyz", np.array([0, 0, 0]), degrees=True).as_matrix()   
    hand_tf = np.eye(4)
    hand_tf[:3, 3] = hand_init_pos
    hand_tf[:3, :3] = hand_init_rot
    
    model.finalize()    

    # ============================== Setup Physics Integrator ==============================
    integrator = IPCIntegrator()
    integrator.use_hard_kinematic_constraint = False
    integrator.use_cpu = False
    integrator.dt = 1 / 25
    integrator.max_newton_iter = 30
    integrator.use_inversion_free_step_size_filter = True
    integrator.inversion_free_im_tol = 1e-6
    integrator.inversion_free_cubic_coef_tol = 1e-10

    # initial
    model.set_robot_states([initial_qpos], hand_tf[None])
    # ============================== Grasping the Handle ==============================
    viz_env = 0
    hand_q = {}
    sim_time = 0.0 
    FIRST_STEPS_GRASPS = 10
    SECOND_STEPS_GRASPS = 10 
    lift_height = 0.0
    for t in range(FIRST_STEPS_GRASPS + SECOND_STEPS_GRASPS):
        if t < FIRST_STEPS_GRASPS:
            interp_q = initial_qpos + (middle_qpos - initial_qpos) * t/FIRST_STEPS_GRASPS
            model.set_robot_targets([dict(zip(joint_names, interp_q))], None)
        else:            
            lift_ratio = (t - FIRST_STEPS_GRASPS + 1) / SECOND_STEPS_GRASPS
            lift_height = 0.2 + 0.01 * lift_ratio  
            
            hand_tf[:3, 3] = [ 0 , 0 , lift_height ]   
            model.set_robot_targets([dict(zip(joint_names, interp_q))], hand_tf[None])

        joint_state = model.get_joint_value(joint_handle)
        
        integrator.simulate(model, dt=1 / (FIRST_STEPS_GRASPS + SECOND_STEPS_GRASPS))

        sim_time += integrator.profile_helper.current_timestep_data["total_timestep"]
        tqdm.write(f"Curr sim speed {(t + 1) / sim_time} FPS")
    
    
        all_rgbs, all_depths, all_normals = model.render_tactile(True, True) 
        
               
        ply_path = osp.join(OUT_DIR, 'frames', f'frame_{model.frame}.ply')
        model.write_scene(ply_path)  
        model.ply_paths[0].append(ply_path)  
         
       

if __name__ == "__main__":
    run()
    cv2.destroyAllWindows()

```

**Comment by XiaodaoLin01** [comment]
It occurred to us that maybe you could provide an example of a simple grab and lift scenario for other hand (e.g. allegro). Then I replace leap with that.
If it's convenient for you.

Best，
Lin

**Comment by XiaodaoLin01** [comment]
> I uploaded the urdf file and the matching .stl, . pkl and .vtk files. Recently, it was discovered that when the num_envs becomes 4 or more, the model can be loaded normally, but there is no gravity and haptics.
> 
> [leap.zip](https://github.com/user-attachments/files/20941901/leap.zip)

We re-examined our conversation. I've found that .json file may not have been added to .zip file. I hope it will be helpful for your further understanding.

[tac_fabr_1e-07.json](https://github.com/user-attachments/files/20972812/tac_fabr_1e-07.json)

**Comment by g1n0st** [comment]
Hi @XiaodaoLin01,

Thank you for sharing the single environment code and assets. It was really helpful and confirmed that your URDF file is not the issue. One problem I can confidently identify in the original script (which also caused the incorrect PLY export) is that `set_robot_targets` should be used instead of `set_robot_states`:

> ``` Python
> for t in range(total_steps):
>         joint_targets_list = []
>         root_targets_list = [] 
>         if t < FIRST_STEPS_GRASPS:   
>             interp_q = initial_qpos + (middle_qpos - initial_qpos) * (t / FIRST_STEPS_GRASPS)
>             joint_targets_list =  [interp_q] * args.num_envs  
>             root_targets_list = root_transforms_list            
>         else:           
>             lift_ratio = (t - FIRST_STEPS_GRASPS) / SECOND_STEPS_GRASPS
>             lift_height = 0.2 + 0.01 * lift_ratio  
>             for env_id in range(args.num_envs):
>             
>                 env_hand_tf = hand_tf.copy()
>                 env_hand_tf[:3, 3] += ([0, 0, lift_height] + env_translation * env_id)
>                 root_targets_list.append(env_hand_tf)
>             
>             joint_targets_list = [middle_qpos] * args.num_envs
>             
>         
>         model.set_robot_states(joint_targets_list, root_targets_list)  # Here should be set_robot_targets
> ```

I'm still inspecting the `world_revolute_joints`-related issue—I believe there might be additional bugs there—and I will keep you posted.

Thanks again for your patience.

Best,
Chang

**Comment by XiaodaoLin01** [comment]
Based on the information you provided, we're glad we've solved all questions!
Thank you for your patience, care and generosity along the way!
Once again, I will firmly follow your project.

Best，
Lin
